<div class="jumbotron">
    <h1>REST API demo</h1>
    <p>This is a simple interface to showcase the methods available in the REST API.</p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default" id="get-list">
            <a class="btn btn-success pull-right" href="#">Execute<i class="glyphicon glyphicon-chevron-right"></i></a>
            <div class="panel-heading">
                <h3 class="panel-title">Get a collection of customers</h3>
            </div>
            <div class="panel-body">
                <p><code>GET /customers</code></p>
                <p class="response-wrapper hidden">
                    <strong>Response:</strong>
                    <pre class="response-placeholder hidden"></pre>
                </p>
            </div>
        </div>
    </div>
    
     <div class="col-md-4">
        <div class="panel panel-default" id="create">
            <a class="btn btn-success pull-right" href="#">Execute<i class="glyphicon glyphicon-chevron-right"></i></a>
            <div class="panel-heading">              
                <h3 class="panel-title">Create a new customer</h3>                
            </div>
            <div class="panel-body">
                <p><code>POST /customers</code></p>
                <p><strong>Parameters:</strong>
                <textarea id="create-payload"></textarea>
                </p>
                <p class="response-wrapper hidden">
                    <strong>Response:</strong>
                    <pre class="response-placeholder hidden"></pre>
                </p>
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default" id="get">
            <a class="btn btn-success pull-right" href="#">Execute<i class="glyphicon glyphicon-chevron-right"></i></a>
            <div class="panel-heading">
                <h3 class="panel-title">Get an individual customer</h3>
            </div>
            <div class="panel-body">
                <p><code>GET /customers/<input id="get-customer-id" placeholder=":id"></input></code></p>
                <p class="response-wrapper hidden">
                    <strong>Response:</strong>
                    <pre class="response-placeholder hidden"></pre>
                </p>
            </div>
        </div>
    </div>
    
</div>
<div class="row">
    
    <div class="col-md-4">
        <div class="panel panel-default" id="update">
            <a class="btn btn-success pull-right" href="#">Execute<i class="glyphicon glyphicon-chevron-right"></i></a>
            <div class="panel-heading">
                <h3 class="panel-title">Update a customer</h3>
            </div>
            <div class="panel-body">
                <p><code>PUT /customers/<input id="update-customer-id" placeholder=":id"></input></code></p>
                <p><strong>Parameters:</strong>
                <textarea id="update-payload"></textarea>
                </p>
                <p class="response-wrapper hidden">
                    <strong>Response:</strong>
                    <pre class="response-placeholder hidden"></pre>
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default" id="delete">
            <a class="btn btn-success pull-right" href="#">Execute<i class="glyphicon glyphicon-chevron-right"></i></a>
            <div class="panel-heading">
                <h3 class="panel-title">Delete a customer</h3>
            </div>
            <div class="panel-body">
                <p><code>DELETE /customers/<input id="delete-customer-id" placeholder=":id"></input></code></p>
                <p class="response-wrapper hidden">
                    <strong>Response:</strong>
                    <pre class="response-placeholder hidden"></pre>
                </p>
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default" id="search">
            <a class="btn btn-success pull-right" href="#">Execute<i class="glyphicon glyphicon-chevron-right"></i></a>
            <div class="panel-heading">
                <h3 class="panel-title">Search for customers</h3>
            </div>
            <div class="panel-body">
                <p><code>GET /customers/search</code></p>
                <p><strong>Parameters:</strong></p>
                <p>
                    <label for="search-id">customerId</label> <input id="search-id" placeholder=":customerId"></input><br>
                    <label for="search-lastname">lastName</label> <input id="search-lastname" placeholder=":lastName"></input><br>
                    <label for="search-email">email</label> <input id="search-email" placeholder=":email"></input>
                </p>
                <p class="response-wrapper hidden">
                    <strong>Response:</strong>
                    <pre class="response-placeholder hidden"></pre>
                </p>
            </div>
        </div>
    </div>
    
</div>
